version: '3'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      TZ: 'Europe/Amsterdam'
    ports:
      - "3306:3306"
    restart: always

  php:
    image: chanto/wp-bedrock:latest
    volumes:
      - ./www:/app
      - ./docker/php/${ENVIRONMENT}.php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - mysql
    restart: always

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./www:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf      
    ports:
      - "80:80"
    depends_on:
      - php
    restart: always

volumes:
  mysql_data:
